/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.personservice.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.personservice.model.PersonDetails;
import com.personservice.model.PersonDetailsModel;
import com.personservice.model.PersonDetailsSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PersonDetails service. Represents a row in the &quot;persondetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PersonDetailsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PersonDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersonDetailsImpl
 * @see PersonDetails
 * @see PersonDetailsModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PersonDetailsModelImpl extends BaseModelImpl<PersonDetails>
	implements PersonDetailsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a person details model instance should use the {@link PersonDetails} interface instead.
	 */
	public static final String TABLE_NAME = "persondetails";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "PersonDetailId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "FirstName", Types.VARCHAR },
			{ "SecondName", Types.VARCHAR },
			{ "Age", Types.INTEGER },
			{ "Specialty", Types.VARCHAR },
			{ "Experience", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PersonDetailId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("FirstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SecondName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Age", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Specialty", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Experience", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table persondetails (uuid_ VARCHAR(75) null,PersonDetailId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,FirstName VARCHAR(75) null,SecondName VARCHAR(75) null,Age INTEGER,Specialty VARCHAR(75) null,Experience VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table persondetails";
	public static final String ORDER_BY_JPQL = " ORDER BY personDetails.FirstName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY persondetails.FirstName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.personservice.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.personservice.model.PersonDetails"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.personservice.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.personservice.model.PersonDetails"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.personservice.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.personservice.model.PersonDetails"),
			true);
	public static final long FIRSTNAME_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long USERID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PersonDetails toModel(PersonDetailsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PersonDetails model = new PersonDetailsImpl();

		model.setUuid(soapModel.getUuid());
		model.setPersonDetailId(soapModel.getPersonDetailId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setFirstName(soapModel.getFirstName());
		model.setSecondName(soapModel.getSecondName());
		model.setAge(soapModel.getAge());
		model.setSpecialty(soapModel.getSpecialty());
		model.setExperience(soapModel.getExperience());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PersonDetails> toModels(PersonDetailsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PersonDetails> models = new ArrayList<PersonDetails>(soapModels.length);

		for (PersonDetailsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.personservice.service.util.ServiceProps.get(
				"lock.expiration.time.com.personservice.model.PersonDetails"));

	public PersonDetailsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _PersonDetailId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPersonDetailId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _PersonDetailId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PersonDetails.class;
	}

	@Override
	public String getModelClassName() {
		return PersonDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("PersonDetailId", getPersonDetailId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("FirstName", getFirstName());
		attributes.put("SecondName", getSecondName());
		attributes.put("Age", getAge());
		attributes.put("Specialty", getSpecialty());
		attributes.put("Experience", getExperience());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long PersonDetailId = (Long)attributes.get("PersonDetailId");

		if (PersonDetailId != null) {
			setPersonDetailId(PersonDetailId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String FirstName = (String)attributes.get("FirstName");

		if (FirstName != null) {
			setFirstName(FirstName);
		}

		String SecondName = (String)attributes.get("SecondName");

		if (SecondName != null) {
			setSecondName(SecondName);
		}

		Integer Age = (Integer)attributes.get("Age");

		if (Age != null) {
			setAge(Age);
		}

		String Specialty = (String)attributes.get("Specialty");

		if (Specialty != null) {
			setSpecialty(Specialty);
		}

		String Experience = (String)attributes.get("Experience");

		if (Experience != null) {
			setExperience(Experience);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPersonDetailId() {
		return _PersonDetailId;
	}

	@Override
	public void setPersonDetailId(long PersonDetailId) {
		_PersonDetailId = PersonDetailId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_FirstName == null) {
			return StringPool.BLANK;
		}
		else {
			return _FirstName;
		}
	}

	@Override
	public void setFirstName(String FirstName) {
		_columnBitmask = -1L;

		if (_originalFirstName == null) {
			_originalFirstName = _FirstName;
		}

		_FirstName = FirstName;
	}

	public String getOriginalFirstName() {
		return GetterUtil.getString(_originalFirstName);
	}

	@JSON
	@Override
	public String getSecondName() {
		if (_SecondName == null) {
			return StringPool.BLANK;
		}
		else {
			return _SecondName;
		}
	}

	@Override
	public void setSecondName(String SecondName) {
		_SecondName = SecondName;
	}

	@JSON
	@Override
	public int getAge() {
		return _Age;
	}

	@Override
	public void setAge(int Age) {
		_Age = Age;
	}

	@JSON
	@Override
	public String getSpecialty() {
		if (_Specialty == null) {
			return StringPool.BLANK;
		}
		else {
			return _Specialty;
		}
	}

	@Override
	public void setSpecialty(String Specialty) {
		_Specialty = Specialty;
	}

	@JSON
	@Override
	public String getExperience() {
		if (_Experience == null) {
			return StringPool.BLANK;
		}
		else {
			return _Experience;
		}
	}

	@Override
	public void setExperience(String Experience) {
		_Experience = Experience;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				PersonDetails.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PersonDetails.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PersonDetails toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PersonDetails)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PersonDetailsImpl personDetailsImpl = new PersonDetailsImpl();

		personDetailsImpl.setUuid(getUuid());
		personDetailsImpl.setPersonDetailId(getPersonDetailId());
		personDetailsImpl.setGroupId(getGroupId());
		personDetailsImpl.setCompanyId(getCompanyId());
		personDetailsImpl.setUserId(getUserId());
		personDetailsImpl.setUserName(getUserName());
		personDetailsImpl.setCreateDate(getCreateDate());
		personDetailsImpl.setModifiedDate(getModifiedDate());
		personDetailsImpl.setFirstName(getFirstName());
		personDetailsImpl.setSecondName(getSecondName());
		personDetailsImpl.setAge(getAge());
		personDetailsImpl.setSpecialty(getSpecialty());
		personDetailsImpl.setExperience(getExperience());

		personDetailsImpl.resetOriginalValues();

		return personDetailsImpl;
	}

	@Override
	public int compareTo(PersonDetails personDetails) {
		int value = 0;

		value = getFirstName().compareTo(personDetails.getFirstName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PersonDetails)) {
			return false;
		}

		PersonDetails personDetails = (PersonDetails)obj;

		long primaryKey = personDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PersonDetailsModelImpl personDetailsModelImpl = this;

		personDetailsModelImpl._originalUuid = personDetailsModelImpl._uuid;

		personDetailsModelImpl._originalGroupId = personDetailsModelImpl._groupId;

		personDetailsModelImpl._setOriginalGroupId = false;

		personDetailsModelImpl._originalCompanyId = personDetailsModelImpl._companyId;

		personDetailsModelImpl._setOriginalCompanyId = false;

		personDetailsModelImpl._originalUserId = personDetailsModelImpl._userId;

		personDetailsModelImpl._setOriginalUserId = false;

		personDetailsModelImpl._setModifiedDate = false;

		personDetailsModelImpl._originalFirstName = personDetailsModelImpl._FirstName;

		personDetailsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PersonDetails> toCacheModel() {
		PersonDetailsCacheModel personDetailsCacheModel = new PersonDetailsCacheModel();

		personDetailsCacheModel.uuid = getUuid();

		String uuid = personDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			personDetailsCacheModel.uuid = null;
		}

		personDetailsCacheModel.PersonDetailId = getPersonDetailId();

		personDetailsCacheModel.groupId = getGroupId();

		personDetailsCacheModel.companyId = getCompanyId();

		personDetailsCacheModel.userId = getUserId();

		personDetailsCacheModel.userName = getUserName();

		String userName = personDetailsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			personDetailsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			personDetailsCacheModel.createDate = createDate.getTime();
		}
		else {
			personDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			personDetailsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			personDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		personDetailsCacheModel.FirstName = getFirstName();

		String FirstName = personDetailsCacheModel.FirstName;

		if ((FirstName != null) && (FirstName.length() == 0)) {
			personDetailsCacheModel.FirstName = null;
		}

		personDetailsCacheModel.SecondName = getSecondName();

		String SecondName = personDetailsCacheModel.SecondName;

		if ((SecondName != null) && (SecondName.length() == 0)) {
			personDetailsCacheModel.SecondName = null;
		}

		personDetailsCacheModel.Age = getAge();

		personDetailsCacheModel.Specialty = getSpecialty();

		String Specialty = personDetailsCacheModel.Specialty;

		if ((Specialty != null) && (Specialty.length() == 0)) {
			personDetailsCacheModel.Specialty = null;
		}

		personDetailsCacheModel.Experience = getExperience();

		String Experience = personDetailsCacheModel.Experience;

		if ((Experience != null) && (Experience.length() == 0)) {
			personDetailsCacheModel.Experience = null;
		}

		return personDetailsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", PersonDetailId=");
		sb.append(getPersonDetailId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", FirstName=");
		sb.append(getFirstName());
		sb.append(", SecondName=");
		sb.append(getSecondName());
		sb.append(", Age=");
		sb.append(getAge());
		sb.append(", Specialty=");
		sb.append(getSpecialty());
		sb.append(", Experience=");
		sb.append(getExperience());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.personservice.model.PersonDetails");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PersonDetailId</column-name><column-value><![CDATA[");
		sb.append(getPersonDetailId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>FirstName</column-name><column-value><![CDATA[");
		sb.append(getFirstName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SecondName</column-name><column-value><![CDATA[");
		sb.append(getSecondName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Age</column-name><column-value><![CDATA[");
		sb.append(getAge());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Specialty</column-name><column-value><![CDATA[");
		sb.append(getSpecialty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Experience</column-name><column-value><![CDATA[");
		sb.append(getExperience());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = PersonDetails.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			PersonDetails.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _PersonDetailId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _FirstName;
	private String _originalFirstName;
	private String _SecondName;
	private int _Age;
	private String _Specialty;
	private String _Experience;
	private long _columnBitmask;
	private PersonDetails _escapedModel;
}