/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.personservice.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PersonDetails service. Represents a row in the &quot;persondetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.personservice.model.impl.PersonDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.personservice.model.impl.PersonDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersonDetails
 * @see com.personservice.model.impl.PersonDetailsImpl
 * @see com.personservice.model.impl.PersonDetailsModelImpl
 * @generated
 */
@ProviderType
public interface PersonDetailsModel extends BaseModel<PersonDetails>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a person details model instance should use the {@link PersonDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this person details.
	 *
	 * @return the primary key of this person details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this person details.
	 *
	 * @param primaryKey the primary key of this person details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this person details.
	 *
	 * @return the uuid of this person details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this person details.
	 *
	 * @param uuid the uuid of this person details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the person detail ID of this person details.
	 *
	 * @return the person detail ID of this person details
	 */
	public long getPersonDetailId();

	/**
	 * Sets the person detail ID of this person details.
	 *
	 * @param PersonDetailId the person detail ID of this person details
	 */
	public void setPersonDetailId(long PersonDetailId);

	/**
	 * Returns the group ID of this person details.
	 *
	 * @return the group ID of this person details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this person details.
	 *
	 * @param groupId the group ID of this person details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this person details.
	 *
	 * @return the company ID of this person details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this person details.
	 *
	 * @param companyId the company ID of this person details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this person details.
	 *
	 * @return the user ID of this person details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this person details.
	 *
	 * @param userId the user ID of this person details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this person details.
	 *
	 * @return the user uuid of this person details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this person details.
	 *
	 * @param userUuid the user uuid of this person details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this person details.
	 *
	 * @return the user name of this person details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this person details.
	 *
	 * @param userName the user name of this person details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this person details.
	 *
	 * @return the create date of this person details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this person details.
	 *
	 * @param createDate the create date of this person details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this person details.
	 *
	 * @return the modified date of this person details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this person details.
	 *
	 * @param modifiedDate the modified date of this person details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this person details.
	 *
	 * @return the first name of this person details
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this person details.
	 *
	 * @param FirstName the first name of this person details
	 */
	public void setFirstName(String FirstName);

	/**
	 * Returns the second name of this person details.
	 *
	 * @return the second name of this person details
	 */
	@AutoEscape
	public String getSecondName();

	/**
	 * Sets the second name of this person details.
	 *
	 * @param SecondName the second name of this person details
	 */
	public void setSecondName(String SecondName);

	/**
	 * Returns the age of this person details.
	 *
	 * @return the age of this person details
	 */
	public int getAge();

	/**
	 * Sets the age of this person details.
	 *
	 * @param Age the age of this person details
	 */
	public void setAge(int Age);

	/**
	 * Returns the specialty of this person details.
	 *
	 * @return the specialty of this person details
	 */
	@AutoEscape
	public String getSpecialty();

	/**
	 * Sets the specialty of this person details.
	 *
	 * @param Specialty the specialty of this person details
	 */
	public void setSpecialty(String Specialty);

	/**
	 * Returns the experience of this person details.
	 *
	 * @return the experience of this person details
	 */
	@AutoEscape
	public String getExperience();

	/**
	 * Sets the experience of this person details.
	 *
	 * @param Experience the experience of this person details
	 */
	public void setExperience(String Experience);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PersonDetails personDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PersonDetails> toCacheModel();

	@Override
	public PersonDetails toEscapedModel();

	@Override
	public PersonDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}