/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.autodetservice.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AutoDetails service. Represents a row in the &quot;autodetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.autodetservice.model.impl.AutoDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.autodetservice.model.impl.AutoDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AutoDetails
 * @see com.autodetservice.model.impl.AutoDetailsImpl
 * @see com.autodetservice.model.impl.AutoDetailsModelImpl
 * @generated
 */
@ProviderType
public interface AutoDetailsModel extends BaseModel<AutoDetails>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auto details model instance should use the {@link AutoDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this auto details.
	 *
	 * @return the primary key of this auto details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auto details.
	 *
	 * @param primaryKey the primary key of this auto details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this auto details.
	 *
	 * @return the uuid of this auto details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this auto details.
	 *
	 * @param uuid the uuid of this auto details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the autodetail ID of this auto details.
	 *
	 * @return the autodetail ID of this auto details
	 */
	public long getAutodetailId();

	/**
	 * Sets the autodetail ID of this auto details.
	 *
	 * @param autodetailId the autodetail ID of this auto details
	 */
	public void setAutodetailId(long autodetailId);

	/**
	 * Returns the group ID of this auto details.
	 *
	 * @return the group ID of this auto details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this auto details.
	 *
	 * @param groupId the group ID of this auto details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this auto details.
	 *
	 * @return the company ID of this auto details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this auto details.
	 *
	 * @param companyId the company ID of this auto details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this auto details.
	 *
	 * @return the user ID of this auto details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this auto details.
	 *
	 * @param userId the user ID of this auto details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this auto details.
	 *
	 * @return the user uuid of this auto details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this auto details.
	 *
	 * @param userUuid the user uuid of this auto details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this auto details.
	 *
	 * @return the user name of this auto details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this auto details.
	 *
	 * @param userName the user name of this auto details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this auto details.
	 *
	 * @return the create date of this auto details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this auto details.
	 *
	 * @param createDate the create date of this auto details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this auto details.
	 *
	 * @return the modified date of this auto details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this auto details.
	 *
	 * @param modifiedDate the modified date of this auto details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the model of this auto details.
	 *
	 * @return the model of this auto details
	 */
	@AutoEscape
	public String getModel();

	/**
	 * Sets the model of this auto details.
	 *
	 * @param Model the model of this auto details
	 */
	public void setModel(String Model);

	/**
	 * Returns the vin of this auto details.
	 *
	 * @return the vin of this auto details
	 */
	@AutoEscape
	public String getVIN();

	/**
	 * Sets the vin of this auto details.
	 *
	 * @param VIN the vin of this auto details
	 */
	public void setVIN(String VIN);

	/**
	 * Returns the year of this auto details.
	 *
	 * @return the year of this auto details
	 */
	public int getYear();

	/**
	 * Sets the year of this auto details.
	 *
	 * @param Year the year of this auto details
	 */
	public void setYear(int Year);

	/**
	 * Returns the manufacturer of this auto details.
	 *
	 * @return the manufacturer of this auto details
	 */
	@AutoEscape
	public String getManufacturer();

	/**
	 * Sets the manufacturer of this auto details.
	 *
	 * @param Manufacturer the manufacturer of this auto details
	 */
	public void setManufacturer(String Manufacturer);

	/**
	 * Returns the bodystyle of this auto details.
	 *
	 * @return the bodystyle of this auto details
	 */
	@AutoEscape
	public String getBodystyle();

	/**
	 * Sets the bodystyle of this auto details.
	 *
	 * @param Bodystyle the bodystyle of this auto details
	 */
	public void setBodystyle(String Bodystyle);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AutoDetails autoDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AutoDetails> toCacheModel();

	@Override
	public AutoDetails toEscapedModel();

	@Override
	public AutoDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}